#!/bin/bash

SCRIPTPATH="$( cd "$(dirname "$0")" || exit ; pwd -P )"
SCRIPTPATH/down

# down the last running theme
if [ -f "/tmp/leftwm-theme-down" ]; then
    /tmp/leftwm-theme-down
    rm /tmp/leftwm-theme-down
fi

ln -s "$SCRIPTPATH"/down /tmp/leftwm-theme-down

# load new theme
leftwm command "LoadTheme $SCRIPTPATH/theme.ron"

# set background
if [ -x "$(command -v feh)" ]; then
  feh --bg-fill "$SCRIPTPATH/backgrounds/$((1 + "$RANDOM" % 4)).png"
fi

# start polybar based on each monitor
if [ -x "$(command -v polybar)" ]; then
  pkill polybar
  monitors="$(polybar -m | sed s/:.*// | tac)"
  while read -r display; do
    MONITOR=$display polybar -c "$SCRIPTPATH/polybar.ini" main &> /dev/null &
  done <<< "$monitors"
fi

# start dunst
dunst -conf "$SCRIPTPATH/dunst.ini" &> /dev/null &

