#!/bin/bash

SCRIPTPATH="$( cd "$(dirname "$0")" || exit ; pwd -P )"

#reset background
if [ -x "$(command -v feh)" ]; then
  feh --bg-scale "$SCRIPTPATH/backgrounds/reset.jpg"
fi

leftwm command "UnloadTheme"

pkill polybar
pkill dunst

